title = "SDRM"
baseURL = "https://sowdowdow.github.io/one-click-hugo-cms"
languageCode = "fr-fr"
languageLang = "fr"
paginate = 5
theme = "PaperMod"
[outputs]
home = [ "HTML", "RSS", "JSON" ]
[taxonomies]
category = "categories"
tag = "tags"
[params]
ShowCodeCopyButtons = true
ShowPostNavLinks = true
[menu]
[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts'
weight = -120
[[menu.main]]
identifier = 'search'
name = 'Rechercher 🔎'
url = '/search/'
weight = -90
[[menu.main]]
identifier = 'roadmap'
name = 'Roadmap'
url = '/roadmap/roadmap'
weight = -90
[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = -80
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/about/'
weight = -70
