title: SDRM
baseURL: 'https://www.simondormeau.com/'
languageCode: fr-fr
languageLang: fr
paginate: 5
theme: PaperMod
outputs:
  home:
    - HTML
    - RSS
    - JSON
taxonomies:
  category: categories
  tag: tags
params:
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts
      weight: -120
    - identifier: search
      name: "Rechercher 🔎"
      url: /search/
      weight: -90
    - identifier: roadmap
      name: Roadmap
      url: /roadmap/roadmap
      weight: -90
    - identifier: tags
      name: Tags
      url: /tags/
      weight: -80
    - identifier: about
      name: About
      url: /about/about/
      weight: -70
    - identifier: github
      name: Github
      url: https://github.com/sowdowdow/hugo-blog
      weight: -60
